google_compute:
    json_key_location: "/Volumes/ryvault1/opencontext/keys/opencontext-py-gce.json"

opencontext_vm:
    vm_box: "debian/stretch64"
    repo_branch: "ry-dev2"

    google_provider:
      project_id: "opencontext-py"
      client_email: "raymond.yee@gmail.com"
      zone: "us-central1-f"
      name: "ry-20190729-ry-dev"
      image: "debian-9-stretch-v20190618"
      machine_type: "n1-standard-2"
      disk_size: 100
      vm_box: gce
      ssh_username: 'raymond.yee'
      ssh_private_key_path: "~/.ssh/id_rsa"

opencontext_predb_vm:
    repo_branch: "ry-dev"

    google_provider:
      project_id: "opencontext-py"
      client_email: "raymond.yee@gmail.com"
      zone: "us-central1-f"
      name: "ry-20190729-ry-dev-oc-predeb"
      image: "debian-9-stretch-v20190618"
      machine_type: "n1-standard-2"
      disk_size: 100
      vm_box: gce
      ssh_username: 'raymond.yee'
      ssh_private_key_path: "~/.ssh/id_rsa"


